# Generated by Django 2.2.16 on 2020-10-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('series', models.BooleanField(default=False)),
                ('by', models.CharField(max_length=100)),
                ('imdb', models.FloatField(default=8, max_length=10)),
                ('rotten_tomatoes', models.PositiveIntegerField(default=89, max_length=100)),
                ('date_released', models.DateTimeField(blank=True, null=True)),
                ('date_modify', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('movies_stream', models.CharField(blank=True, max_length=30000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_link', models.CharField(blank=True, max_length=30000, null=True)),
                ('num_of_sessions', models.IntegerField(default=5)),
                ('num_of_episodes', models.IntegerField(default=20)),
                ('action', models.BooleanField(default=False)),
                ('sifi', models.BooleanField(default=False)),
                ('thriller', models.BooleanField(default=False)),
                ('adventure', models.BooleanField(default=False)),
                ('classic', models.BooleanField(default=False)),
                ('Romance', models.BooleanField(default=False)),
                ('animation', models.BooleanField(default=False)),
                ('drama', models.BooleanField(default=False)),
                ('crime', models.BooleanField(default=False)),
                ('mystery', models.BooleanField(default=False)),
                ('family', models.BooleanField(default=False)),
                ('documentary', models.BooleanField(default=False)),
                ('fantasy', models.BooleanField(default=False)),
                ('comedy', models.BooleanField(default=False)),
                ('ep1', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep2', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep3', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep4', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep5', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep6', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep7', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep8', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep9', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep10', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep11', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep12', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep13', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep14', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep15', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep16', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep17', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep18', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep19', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep20', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep21', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep22', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep23', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep24', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep25', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep26', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep27', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep28', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep29', models.CharField(blank=True, max_length=30000, null=True)),
                ('ep30', models.CharField(blank=True, max_length=30000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Movies')),
            ],
        ),
    ]
