# Generated by Django 2.2.16 on 2020-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='advt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
